// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: goproc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoProc_Exec_FullMethodName = "/goproc.GoProc/Exec"
)

// GoProcClient is the client API for GoProc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoProcClient interface {
	Exec(ctx context.Context, in *ExecProcessRequest, opts ...grpc.CallOption) (*ExecProcessResponse, error)
}

type goProcClient struct {
	cc grpc.ClientConnInterface
}

func NewGoProcClient(cc grpc.ClientConnInterface) GoProcClient {
	return &goProcClient{cc}
}

func (c *goProcClient) Exec(ctx context.Context, in *ExecProcessRequest, opts ...grpc.CallOption) (*ExecProcessResponse, error) {
	out := new(ExecProcessResponse)
	err := c.cc.Invoke(ctx, GoProc_Exec_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoProcServer is the server API for GoProc service.
// All implementations must embed UnimplementedGoProcServer
// for forward compatibility
type GoProcServer interface {
	Exec(context.Context, *ExecProcessRequest) (*ExecProcessResponse, error)
	mustEmbedUnimplementedGoProcServer()
}

// UnimplementedGoProcServer must be embedded to have forward compatible implementations.
type UnimplementedGoProcServer struct {
}

func (UnimplementedGoProcServer) Exec(context.Context, *ExecProcessRequest) (*ExecProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedGoProcServer) mustEmbedUnimplementedGoProcServer() {}

// UnsafeGoProcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoProcServer will
// result in compilation errors.
type UnsafeGoProcServer interface {
	mustEmbedUnimplementedGoProcServer()
}

func RegisterGoProcServer(s grpc.ServiceRegistrar, srv GoProcServer) {
	s.RegisterService(&GoProc_ServiceDesc, srv)
}

func _GoProc_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoProcServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoProc_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoProcServer).Exec(ctx, req.(*ExecProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoProc_ServiceDesc is the grpc.ServiceDesc for GoProc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoProc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goproc.GoProc",
	HandlerType: (*GoProcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _GoProc_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goproc.proto",
}
